"""Creating a transaction referece column

Revision ID: 0f74539d5bb8
Revises: e542d29aa993
Create Date: 2023-10-05 02:08:27.342631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f74539d5bb8'
down_revision = 'e542d29aa993'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ref', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_column('ref')

    # ### end Alembic commands ###
