"""Table creation

Revision ID: 385e7c05d31b
Revises: 
Create Date: 2023-09-17 19:46:25.530808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '385e7c05d31b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('has_acc', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)

    op.create_table('customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('first_name', sa.String(length=140), nullable=True),
    sa.Column('last_name', sa.String(length=140), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('phone_number', sa.String(length=204), nullable=True),
    sa.Column('username', sa.String(length=200), nullable=True),
    sa.Column('dob', sa.DateTime(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('bank_name', sa.String(length=240), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_number')
    )
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customer_email'), ['email'], unique=True)

    op.create_table('account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cus_id', sa.Integer(), nullable=True),
    sa.Column('account_number', sa.String(length=100), nullable=False),
    sa.Column('account_pin', sa.String(length=4), nullable=True),
    sa.Column('acc_type', sa.String(length=240), nullable=True),
    sa.Column('balance', sa.Integer(), nullable=True),
    sa.Column('bank_name', sa.String(length=240), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cus_id'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('address',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cus_id', sa.Integer(), nullable=True),
    sa.Column('apartment_number', sa.Integer(), nullable=False),
    sa.Column('street_number', sa.Integer(), nullable=True),
    sa.Column('street_name', sa.String(length=256), nullable=False),
    sa.Column('city', sa.String(length=256), nullable=False),
    sa.Column('state', sa.String(length=256), nullable=False),
    sa.Column('country', sa.String(length=256), nullable=False),
    sa.Column('postal_code', sa.Integer(), nullable=True),
    sa.Column('address_line_2', sa.String(length=400), nullable=True),
    sa.ForeignKeyConstraint(['cus_id'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('acc_num', sa.String(length=100), nullable=True),
    sa.Column('bank_name', sa.String(length=240), nullable=False),
    sa.Column('transaction_type', sa.String(length=240), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['acc_num'], ['account.account_number'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction')
    op.drop_table('address')
    op.drop_table('account')
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customer_email'))

    op.drop_table('customer')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    # ### end Alembic commands ###
