"""MAking some transaction changes

Revision ID: 3ffb97718603
Revises: 83d61d9eca4a
Create Date: 2023-10-03 15:34:42.695366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ffb97718603'
down_revision = '83d61d9eca4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id_creditor', sa.Integer(), nullable=True),
    sa.Column('transaction_id_debitor', sa.Integer(), nullable=True),
    sa.Column('crebitor', sa.Integer(), nullable=True),
    sa.Column('deditor', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['crebitor'], ['account.account_number'], ),
    sa.ForeignKeyConstraint(['deditor'], ['account.account_number'], ),
    sa.ForeignKeyConstraint(['transaction_id_creditor'], ['transaction.id'], ),
    sa.ForeignKeyConstraint(['transaction_id_debitor'], ['transaction.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transact')
    # ### end Alembic commands ###
