"""Adding a req/-close column


Revision ID: 438325eca2c1
Revises: 0f74539d5bb8
Create Date: 2023-10-06 17:18:26.171523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '438325eca2c1'
down_revision = '0f74539d5bb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deleted_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('req_clos', sa.String(length=3), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.drop_column('req_clos')

    op.drop_table('deleted_account')
    # ### end Alembic commands ###
