"""Including a column in closed accounts for the reason for deletion

Revision ID: 83d61d9eca4a
Revises: 1f9e061d6e9d
Create Date: 2023-09-29 08:13:48.316783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83d61d9eca4a'
down_revision = '1f9e061d6e9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('closed_accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('close_reason', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('closed_accounts', schema=None) as batch_op:
        batch_op.drop_column('close_reason')

    # ### end Alembic commands ###
