"""Adding cus_name column to transavtions

Revision ID: e542d29aa993
Revises: 3ffb97718603
Create Date: 2023-10-04 16:26:14.001297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e542d29aa993'
down_revision = '3ffb97718603'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cus_name', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_column('cus_name')

    # ### end Alembic commands ###
